### ISSUE TITLE
Can't drag and move window

### ISSUE THREAD

**Issue by Schamper** [stonesam92/ChitChat#19]
Don't know if this is related to El Capitan or not, but I just updated to 1.2 and I don't seem to be able to move the chat window.

**Comment by stonesam92** [comment]
I'm going to assume this is an El Capitan bug, since ChitChat doesn't do anything particularly special in terms of managing its windows.

Everything it does is standard SDK stuff that's not marked as deprecated, so I'm going to close this issue. 

If its still broken when the GM is out, then I'll reopen and look into it then.

**Comment by ctcampbell** [comment]
The GM is out and its still broken.
