### ISSUE TITLE
Cant move the window...

### ISSUE THREAD

**Issue by DiegoGiovany** [stonesam92/ChitChat#25]
I'm using 10.11, and the chat window appears to not be draggable, this is normal?

**Comment by stonesam92** [comment]
I don't have any device running 10.11 to test on, but ChitChat doesn't use any private or deprecated APIs for managing the window so I'm assuming this is an El Capitan bug.

I'm going to close this issue for now, since I don't believe it to be a bug in ChitChat, and will reopen if the issue persists once the 10.11 GM is released.

Cheers

**Comment by dturton** [comment]
I am experiencing the same issue..

**Comment by hahnalexander** [comment]
Same here but you CAN move it with resizing the corners ; )

**Comment by tobiasmuecksch** [comment]
GM is released an issue still persists! It even persists in Beta Version 10.11.1 too.
(I've tested both).
